### ISSUE TITLE
Image without link

### ISSUE THREAD

**Issue by geraldo** [diggy/wp-bootstrap-carousel#9]
I would like to get rid of the image link, maybe with a new link=0 parameter?

**Comment by diggy** [comment]
@geraldo you can use the `unwrap` param to "unlink" the images (see [this PR](https://github.com/diggy/wp-bootstrap-carousel/pull/5)), e.g.:

`[carousel unwrap="1"]`

**Comment by geraldo** [comment]
I tested this but it didn't work for me so I thought I don't understand the parameter. Now I see the problem: the unwrap parameter doesn't work when controls are turned off. Try this:

```
[carousel controls="0" unwrap="1"]
```

**Comment by diggy** [comment]
@geraldo that seems to work fine for me.. is there a testcase online somewhere, demonstrating the behavior?

**Comment by geraldo** [comment]
@diggy Here you are: http://tbb.kic-innoenergy.com/

There is a carousel almost on every page, all with unwrap option set to 1.

**Comment by diggy** [comment]
@geraldo the problem is caused by another script (I assume) wrapping the images of the carousel with a div having a `tint` class:

In the source code of your site:

```
<a href="http://example.com/image.jpg">
    <div class="tint">
        <img src="http://example.com/image.jpg" data-wpbc_unwrap="1">
    </div>
</a>
```

required markup for the `unwrap` param to do its work:

```
<a href="http://example.com/image.jpg">
    <img src="http://example.com/image.jpg" data-wpbc_unwrap="1">
</a>
```

I hope this is enough info for you to resolve the issue.

In the next release I'll make sure not to target the immediate parent, but use jQuery's `.closest()` to find and unwrap the closest `a` element. Thanks for reporting!

**Comment by geraldo** [comment]
@diggy great, that helped to resolve my issue! Thanks a lot for your great work!
